name: Go

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Deploy to'     
        required: true
        default: 'DEV' 
        type: choice
        options:
        - DEV
        - ST
        - POT
      artifactoryUrl:
        description: 'Your Artifactory URL'
        default: 'myArtifactoryURL.com'  
      artifactoryName:
        description: 'Your Repo Name'
        default: 'myRepoName'
      artifactoryPath:
        description: 'Your Repo path'
        default: 'myRepoPath' 
      artifactoryToken:
        description: 'Your Repo AccessToken'
        default: 'TOKEN String'
      openshiftServer:
        description: 'Your Artifactory URL'
        default: '10.0.0.1:8081'  
      openshiftToken:
        description: 'Your openshift token'
        default: 'TOKEN String'


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
