name: Go

on:
  workflow_dispatch:
    inputs:
      artifactoryUrl:
        description: 'Your Artifactory URL'
        default: 'myArtifactoryURL.com'  
      artifactoryName:
        description: 'Your Repo Name'
        default: 'myRepoName'
      artifactoryPath:
        description: 'Your Repo path'
        default: 'myRepoPath' 
      artifactoryToken:
        description: 'Your Repo AccessToken'
        default: 'TOKEN String'
      openshiftServer:
        description: 'Your Artifactory URL'
        default: '10.0.0.1:8081'  
      openshiftToken:
        description: 'Your openshift token'
        default: 'TOKEN String'


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: setup-java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: validate java version
      run:
        java -version
