on:
  push:
    branches: [main]
jobs:
  steps:
  - name: Create and expose app
    uses: redhat-actions/oc-new-app@v1
    with:
      app_name: petclinic
      image: quay.io/redhat-github-actions/petclinic:v1
      namespace: github-actions-bot-dev
